# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Team 1418
email: robotics1418@gmail.com
description: A FIRST Robotics team in Falls Church, VA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://1418.team" # the base hostname & protocol for your site
twitter_username: robotics1418
github_username:  frc1418

# Build settings
sass:
    style: compressed
exclude:
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json
include:
    - _pages