# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Team 2626
email: firstevolution2626@gmail.com
description: A FIRST Robotics team in Sherbrooke, Québec, Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "evolution2626.com" # the base hostname & protocol for your site
twitter_username: Evolution2626
github_username:  Evolution2626

# These variables are used to handle different languages more easily
# English
enwelcome: Welcometets
enshortdesc: Evolution 2626 short description

endescline1: We are FRC Team Evolution 2626, proudly representing the Séminaire de Sherbrooke in Sherbrooke, Quebec, Canada. Every year, we participate in the famous FIRST Robotics Competition. Since our humble beginnings in 2008, we have evolved into a cooperative of dreamers and achievers. On this website, you will find information on our team, on the FIRST program and resources for other FRC teams.

endescline2: Our mission is to inspire young people to be science and technology leaders, by engaging them in exciting mentor-based programs that build science, engineering and technology skills, that inspire innovation, and that foster well-rounded life capabilities including self-confidence, communication, and leadership.




# Build settings
sass:
    style: compressed
exclude:
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json
include:
    - _pages
